### Site Settings ###
title               : jongeunShin95
description         : >-
                      "I am a student. :eyes:"
baseurl             : "/"                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : jongeunShin95/jongeunshin95.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : jongeunShin95/jongeunshin95.github.io

### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md

mermaid:
  src: '/js/mermaid.js'
  src_config: '/js/mermaid_config.js'


### Author Info ###
author:
  name              : jongeun Shin
  image             : https://avatars2.githubusercontent.com/u/20867824?s=460&u=e69016e31a1310d5b259deedf70517780f796324&v=4
# behance           : your_username
# dribbble          : your_username
  email             : jongeunshin95@gmail.com
#  facebook          : your_username
  github            : jongeunShin95
# gitlab            : your_username
# instagram         : your_username
# linkedin          : your_username
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:                                             # For Documentation Only
    output: true                                        # For Documentation Only


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
